# Podfile
# CocoaPods documentation: https://guides.cocoapods.org/syntax/podfile.html

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
